// Code generated by "stringer -type=BlobErrno -trimprefix=Err"; DO NOT EDIT.

package base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNone-0]
	_ = x[ErrDecompression-1]
	_ = x[ErrChecksumMismatch-2]
	_ = x[ErrIORead-3]
	_ = x[ErrIOWrite-4]
	_ = x[ErrTruncated-5]
	_ = x[ErrInvalidFormat-6]
	_ = x[ErrUnknown-7]
}

const _BlobErrno_name = "NoneDecompressionChecksumMismatchIOReadIOWriteTruncatedInvalidFormatUnknown"

var _BlobErrno_index = [...]uint8{0, 4, 17, 33, 39, 46, 55, 68, 75}

func (i BlobErrno) String() string {
	if i >= BlobErrno(len(_BlobErrno_index)-1) {
		return "BlobErrno(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlobErrno_name[_BlobErrno_index[i]:_BlobErrno_index[i+1]]
}
